### ISSUE TITLE
Cannot build on Ubuntu 22.04 Windows WSL2: Cannot find module 'dmg-license'

### ISSUE THREAD

**Issue by tinymins** [jooy2/vutron#155]
**Describe the bug**
Just clone, install, and build. Cannot build.

**To Reproduce**
1. clone
2. npm i
3. npm run build

**Expected behavior**
Build something, like bin files

**Device information (please complete the following information):**
 - OS Name: Ubuntu 22.04 on WSL2
 - OS Version: 22.04

**Screenshots & Attachments**
```
# emil @ Ubuntu-2204-WSL2 in ~/Developments/Github/vutron on git:master o [22:44:28] 
$ npm i
npm WARN deprecated @types/jszip@3.4.1: This is a stub types definition. jszip provides its own type definitions, so you do not need this installed.

added 652 packages, and audited 653 packages in 4s

153 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

# emil @ Ubuntu-2204-WSL2 in ~/Developments/Github/vutron on git:master o [22:44:33] 
$ npm run build

> vutron@1.0.0 build
> npm run build:pre && electron-builder --config=buildAssets/builder/config.ts -wml


> vutron@1.0.0 build:pre
> npm run format:fix && vue-tsc --noEmit && vite build


> vutron@1.0.0 format:fix
> prettier . --write

.eslintrc.json 21ms
.prettierrc 11ms
buildAssets/builder/config.ts 86ms
CODE_OF_CONDUCT.md 30ms
docs/package.json 1ms
docs/src/.vitepress/config.mts 6ms
docs/src/automated-testing.md 5ms
docs/src/build-configuration.md 7ms
docs/src/getting-started.md 6ms
docs/src/install-local-documentation.md 2ms
docs/src/main-and-renderer-process.md 7ms
docs/src/npm-scripts.md 7ms
docs/src/other-projects.md 2ms
docs/src/pre-configured-components.md 2ms
docs/src/project-structure.md 2ms
docs/tsconfig.json 1ms
package.json 1ms
playwright.config.ts 1ms
README.ko-KR.md 9ms
README.md 5ms
README.zh-CN.md 8ms
src/main/index.ts 7ms
src/main/IPCs.ts 4ms
src/main/MainRunner.ts 9ms
src/main/utils/Constants.ts 3ms
src/main/utils/Menus.ts 2ms
src/preload/index.ts 4ms
src/renderer/App.vue 22ms
src/renderer/components/layout/DefaultLayout.vue 2ms
src/renderer/components/layout/HeaderLayout.vue 11ms
src/renderer/components/layout/index.ts 1ms
src/renderer/index.html 1ms
src/renderer/locales/de.json 1ms
src/renderer/locales/en.json 1ms
src/renderer/locales/es.json 1ms
src/renderer/locales/fr.json 0ms
src/renderer/locales/ja.json 1ms
src/renderer/locales/ko.json 1ms
src/renderer/locales/pt.json 0ms
src/renderer/locales/ru.json 1ms
src/renderer/locales/zh-hans.json 1ms
src/renderer/locales/zh-hant.json 1ms
src/renderer/main.ts 2ms
src/renderer/plugins/i18n.ts 1ms
src/renderer/plugins/vuetify.ts 2ms
src/renderer/router/index.ts 1ms
src/renderer/screens/ErrorScreen.vue 1ms
src/renderer/screens/index.ts 0ms
src/renderer/screens/MainScreen.vue 16ms
src/renderer/screens/SecondScreen.vue 1ms
src/renderer/store/counter.ts 2ms
src/renderer/utils/index.ts 2ms
src/vue-shim.d.ts 1ms
tests/app.spec.ts 5ms
tsconfig.json 1ms
tsconfig.node.json 1ms
vite.config.ts 4ms
vite v4.4.9 building for production...
✓ 308 modules transformed.
../../dist/index.html                                      0.26 kB │ gzip:   0.19 kB
../../dist/materialdesignicons-webfont-c1c004a9.woff2    396.73 kB
../../dist/materialdesignicons-webfont-80bb28b3.woff     576.75 kB
../../dist/materialdesignicons-webfont-a58ecb54.ttf    1,279.99 kB
../../dist/materialdesignicons-webfont-67d24abe.eot    1,280.21 kB
../../dist/index-54c5d3cf.css                            631.54 kB │ gzip:  91.62 kB
../../dist/index-81511a61.js                             331.95 kB │ gzip: 115.91 kB
✓ built in 1.71s
vite v4.4.9 building for production...
✓ 346 modules transformed.
dist/main/index.js  280.33 kB │ gzip: 86.07 kB
✓ built in 680ms
vite v4.4.9 building for production...
✓ 1 modules transformed.
dist/preload/index.js  0.61 kB │ gzip: 0.32 kB
✓ built in 6ms
  • electron-builder  version=24.6.4 os=5.15.90.1-microsoft-standard-WSL2
compiling: [
  '/home/emil/Developments/Github/vutron/buildAssets/builder/config.ts'
]
  • loaded configuration  file=/home/emil/Developments/Github/vutron/buildAssets/builder/config.ts
  • writing effective config  file=release/1.0.0/builder-effective-config.yaml
  ⨯ Cannot find module 'dmg-license'
Require stack:
- /home/emil/Developments/Github/vutron/node_modules/dmg-builder/out/dmgLicense.js
- /home/emil/Developments/Github/vutron/node_modules/dmg-builder/out/dmg.js
- /home/emil/Developments/Github/vutron/node_modules/dmg-builder/out/dmgUtil.js
- /home/emil/Developments/Github/vutron/node_modules/app-builder-lib/out/macPackager.js
- /home/emil/Developments/Github/vutron/node_modules/app-builder-lib/out/packager.js
- /home/emil/Developments/Github/vutron/node_modules/app-builder-lib/out/index.js
- /home/emil/Developments/Github/vutron/node_modules/electron-builder/out/builder.js
- /home/emil/Developments/Github/vutron/node_modules/electron-builder/out/cli/cli.js
- /home/emil/Developments/Github/vutron/node_modules/electron-builder/cli.js  failedTask=build stackTrace=Error: Cannot find module 'dmg-license'
Require stack:
- /home/emil/Developments/Github/vutron/node_modules/dmg-builder/out/dmgLicense.js
- /home/emil/Developments/Github/vutron/node_modules/dmg-builder/out/dmg.js
- /home/emil/Developments/Github/vutron/node_modules/dmg-builder/out/dmgUtil.js
- /home/emil/Developments/Github/vutron/node_modules/app-builder-lib/out/macPackager.js
- /home/emil/Developments/Github/vutron/node_modules/app-builder-lib/out/packager.js
- /home/emil/Developments/Github/vutron/node_modules/app-builder-lib/out/index.js
- /home/emil/Developments/Github/vutron/node_modules/electron-builder/out/builder.js
- /home/emil/Developments/Github/vutron/node_modules/electron-builder/out/cli/cli.js
- /home/emil/Developments/Github/vutron/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/emil/Developments/Github/vutron/node_modules/dmg-builder/src/dmgLicense.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/emil/Developments/Github/vutron/node_modules/dmg-builder/src/dmg.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)

# emil @ Ubuntu-2204-WSL2 in ~/Developments/Github/vutron on git:master o [22:44:46] C:1
$ 
```

**Additional context**

**Comment by jooy2** [comment]
hello. Thank you for using `Vutron`.

The `npm run build` script is a cross-compile build script that builds packages for Windows, Mac, and Linux and is not optimized for Linux (specifically for macOS).
As a result, this script is recommended for use on macOS.

To build Linux packages separately, try running `npm run build:linux`.

Reference: https://www.electron.build/multi-platform-build

Regards,

**Comment by tinymins** [comment]
Thanks, that means I have to run build on Windows hosted node instead of WSL2 Ubuntu to get a windows `.exe` file?

**Comment by tinymins** [comment]
Thanks a lot! I'll try to test how to cross-platform build on Linux. Maybe I can do some contribution for `Vutron` if I got successful builds.

**Comment by jooy2** [comment]
Thanks! I'm on vacation and can't work on the project right now, but I'll try to improve the description of the cross-platform build as soon as I can :)

**Comment by jooy2** [comment]
In the latest code, the scripts are now separated into `npm run build` (build the package for the current OS) and `npm run build:all` (multiplatform build).

If you encounter any new issues, please open a new issue. I'll close this issue.

Regards,
